'use client';

import React from 'react';
import { EmptyState } from '../workspace/EmptyState';
import { ShieldCheck } from 'lucide-react';

export const AuditTimeline: React.FC = () => {
  return (
    <div className="table-responsive-wrapper">
      <EmptyState
        title="Audit Log Stream Empty"
        description="Statutory security audit events, credential modifications, and record endorsement logs will appear here when generated by active operations."
        icon={ShieldCheck}
      />
    </div>
  );
};
