import os
import json
import urllib.request
import urllib.error
import time
from typing import List, Dict, Any, Optional
from app.providers.base_document_text_provider import BaseDocumentTextProvider

class LlamaDocumentTextProvider(BaseDocumentTextProvider):
    """
    Server-Side Llama API Document Text Extraction Provider.
    Receives real processed document/page images generated by the OpenCV preprocessing stage,
    and extracts Telugu & English text faithfully using Llama API / LlamaCloud.
    """

    PROVIDER_ID = "PROV-LLAMA-TEXT"
    PROVIDER_NAME = "Llama Document Text Extraction Engine"

    @property
    def provider_id(self) -> str:
        return self.PROVIDER_ID

    @property
    def provider_name(self) -> str:
        return self.PROVIDER_NAME

    def get_api_key(self) -> str:
        return (
            os.environ.get("LLAMA_API_KEY")
            or os.environ.get("LLAMA_CLOUD_API_KEY")
            or ""
        ).strip()

    def get_base_url(self) -> str:
        if os.environ.get("LLAMA_API_BASE_URL"):
            return os.environ.get("LLAMA_API_BASE_URL", "").rstrip("/")
        key = self.get_api_key()
        if key.startswith("llx-"):
            return "https://api.cloud.llamaindex.ai/api/v1"
        return "https://api.llama-api.com"

    def get_model(self) -> str:
        return os.environ.get("LLAMA_MODEL", "agentic-latest")

    def health_check(self) -> Dict[str, Any]:
        key = self.get_api_key().strip()
        configured = bool(key)
        return {
            "providerId": self.PROVIDER_ID,
            "providerName": self.PROVIDER_NAME,
            "configured": configured,
            "model": self.get_model(),
            "baseUrl": self.get_base_url(),
            "status": "READY" if configured else "LLAMA_KEY_MISSING",
        }

    def extract_document_text(
        self, pages: List[Dict[str, Any]], metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        api_key = self.get_api_key()
        model = self.get_model()
        base_url = self.get_base_url()
        start_time = time.time()

        if not api_key:
            print("[LLAMA] Extraction aborted: LLAMA_API_KEY unconfigured.")
            return {
                "success": False,
                "error": "LLAMA_API_KEY is not configured on the server. Please set LLAMA_API_KEY in the environment.",
                "status": "LLAMA_KEY_MISSING",
                "provider": self.PROVIDER_ID,
                "model": model,
                "pages": [],
                "fullText": "",
                "processingMetadata": {
                    "processingTimeMs": int((time.time() - start_time) * 1000),
                },
            }

        if not pages:
            return {
                "success": False,
                "error": "No pages provided for text extraction.",
                "status": "EMPTY_PAGES",
                "provider": self.PROVIDER_ID,
                "model": model,
                "pages": [],
                "fullText": "",
                "processingMetadata": {
                    "processingTimeMs": int((time.time() - start_time) * 1000),
                },
            }

        print(f"[LLAMA] request started (model: {model}, pages: {len(pages)})")

        extracted_pages = []
        full_text_parts = []
        overall_language = "te"

        endpoint = f"{base_url}/chat/completions"

        for page in pages:
            page_num = page.get("pageNumber", 1)
            b64_img = page.get("base64Preview") or page.get("imageBase64") or ""
            image_url = b64_img if b64_img.startswith("data:") else f"data:image/jpeg;base64,{b64_img}"

            system_prompt = (
                "You are an expert document text transcription engine for Indian revenue and historical land-record documents (Telugu and English).\n"
                "Extract all visible text from the document page verbatim.\n"
                "Rules:\n"
                "1. Transcribe printed and handwritten Telugu and English text accurately.\n"
                "2. Preserve structural layouts, tabular lines, survey numbers, khata numbers, names, and extents.\n"
                "3. Do NOT invent or hallucinate text that is not visible on the document.\n"
                "4. Return only the extracted document text."
            )

            user_content: List[Dict[str, Any]] = [
                {
                    "type": "text",
                    "text": f"Please transcribe all visible text from this historical land-record page (Page {page_num}).",
                }
            ]

            if b64_img:
                user_content.append({
                    "type": "image_url",
                    "image_url": {
                        "url": image_url
                    }
                })

            req_payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content},
                ],
                "temperature": 0.1,
                "max_tokens": 2048,
            }

            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
                "User-Agent": "e-Bhoomi-LlamaProvider/1.0",
            }

            page_text = ""
            try:
                req_data = json.dumps(req_payload).encode("utf-8")
                req = urllib.request.Request(endpoint, data=req_data, headers=headers, method="POST")
                with urllib.request.urlopen(req, timeout=45) as resp:
                    resp_json = json.loads(resp.read().decode("utf-8"))
                    page_text = resp_json.get("choices", [{}])[0].get("message", {}).get("content", "").strip()
            except urllib.error.HTTPError as http_err:
                err_body = http_err.read().decode("utf-8", errors="replace")[:200]
                is_auth_err = http_err.code in (401, 403)
                is_model_err = (
                    http_err.code == 404
                    or (http_err.code == 400 and ("model" in err_body.lower() or "not found" in err_body.lower()))
                )
                status = (
                    "LLAMA_AUTH_FAILED"
                    if is_auth_err
                    else "LLAMA_MODEL_UNAVAILABLE"
                    if is_model_err
                    else "LLAMA_REQUEST_FAILED"
                )
                print(f"[LLAMA] request error ({http_err.code}): {err_body[:100]}")
                return {
                    "success": False,
                    "error": f"Llama API Error {http_err.code}: {err_body}",
                    "status": status,
                    "provider": self.PROVIDER_ID,
                    "model": model,
                    "pages": extracted_pages,
                    "fullText": "\n\n".join(full_text_parts),
                    "processingMetadata": {
                        "failedAtPage": page_num,
                        "processingTimeMs": int((time.time() - start_time) * 1000),
                    },
                }
            except Exception as exc:
                print(f"[LLAMA] request failed: {str(exc)}")
                return {
                    "success": False,
                    "error": f"Llama Request Failed: {str(exc)}",
                    "status": "LLAMA_REQUEST_FAILED",
                    "provider": self.PROVIDER_ID,
                    "model": model,
                    "pages": extracted_pages,
                    "fullText": "\n\n".join(full_text_parts),
                    "processingMetadata": {
                        "failedAtPage": page_num,
                        "processingTimeMs": int((time.time() - start_time) * 1000),
                    },
                }

            is_primarily_english = any(c.isascii() and c.isalpha() for c in page_text) and not any(
                "\u0c00" <= c <= "\u0c7f" for c in page_text
            )
            page_lang = "en" if is_primarily_english else "te"
            if page_lang == "en" and overall_language == "te" and len(extracted_pages) == 0:
                overall_language = "en"

            extracted_pages.append({
                "pageNumber": page_num,
                "text": page_text,
                "language": page_lang,
                "source": "llama",
            })
            full_text_parts.append(page_text)

        full_text = "\n\n".join(full_text_parts)
        print("[LLAMA] request completed")
        print(f"[LLAMA] text characters returned: {len(full_text)}")

        if not full_text.strip():
            return {
                "success": False,
                "status": "TEXT_EXTRACTION_EMPTY",
                "provider": self.PROVIDER_ID,
                "model": model,
                "language": overall_language,
                "pageCount": len(extracted_pages),
                "pages": extracted_pages,
                "fullText": "",
                "error": "Llama returned empty text for the uploaded document.",
                "processingMetadata": {
                    "processingTimeMs": int((time.time() - start_time) * 1000),
                },
            }

        return {
            "success": True,
            "status": "COMPLETED",
            "provider": self.PROVIDER_ID,
            "model": model,
            "language": overall_language,
            "pageCount": len(extracted_pages),
            "pages": extracted_pages,
            "fullText": full_text,
            "processingMetadata": {
                "processingTimeMs": int((time.time() - start_time) * 1000),
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            },
        }
